[build]
  builder = "nixpacks"
  buildCommand = "cd backend && go build -o main ."

[deploy]
  startCommand = "/main"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[env]
  PORT = "4000"
